version: '3.1'  

services:

  ethereum-node:
    image: ethereum/client-go:v1.8.21
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./ethereum:/root
    entrypoint:
      - /root/run.sh

  db:
    image: postgres:11.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
